# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(blank=True, default='', max_length=100)),
                ('person', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
